# Generated by Django 3.0.6 on 2020-05-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20200521_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='completion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2020-05-24'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2020-05-24'),
        ),
    ]
