# Generated by Django 3.0.6 on 2020-06-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20200524_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='dueness',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2020-06-04'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2020-06-04'),
        ),
    ]
