# Generated by Django 3.0.6 on 2020-06-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_auto_20200607_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dueness',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
