# Generated by Django 3.0.6 on 2020-06-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0011_auto_20200607_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(default='2020-06-09'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default='2020-06-09'),
        ),
    ]
